demosite/countrydemo/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', TemplateView.as_view(
        template_name='countrydemo/about.html'),
        name='country-demo-about'),
    url(r'^country-pages/', views.wikipedia_pages,
        name='country-pages'),
    url(r'^info/$', views.CountryInfoListView.as_view(),
        name='country-info-list-view'),
    url(r'^info/(?P<pk>\d+)/$', views.CountryInfoDetailView.as_view(),
        name='country-info-detail-view'),
    url(r'^info/update/(?P<pk>\d+)', views.CountryInfoUpdateView.as_view(),
        name='country-info-update-view'),
]

demosite/demosite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='homepage.html'), name='homepage'),
    url(r'^countrydemo/', include('countrydemo.urls', namespace='countrydemo')),
    url(r'^admin/', admin.site.urls),
]

demosite/countrydemo/models.py
'''
Models for the Country Demo app
'''

from django.db import models
from django_countries.fields import CountryField


class CountryInfo(models.Model):
    '''
    A  model to demonstrate linking models with the `CountryField`
    '''
    country = CountryField()
    notes = models.TextField()

    def __repr__(self):
        return '{}'.format(self.country.name)

    def __str__(self):
        return str(self.__repr__())

    def __unicode__(self):
        return u'{}'.format(self.__repr__())


class LinkSet(models.Model):
    '''
    Defines a set of links to Country information on an external site
    A site can have different source types, so the 'host' field is not uniqwue
    But the 'label' and 'source_url' are unique.

    The source url is the URL of the aggregation/list page that links to specific countries.

    TODO: Change source_url to NOT be unique, so that we can make it null for sources that
    are not screen scraped
    '''
    label = models.CharField(max_length=100, unique=True)
    host = models.URLField()
    source_url = models.URLField(unique=True)

    def __repr__(self):
        return '{},{},{},{}'.format(self.id, self.label, self.host, self.source_url)

    def __str__(self):
        return str(self.__repr__())

    def __unicode__(self):
        return u'{}'.format(self.__repr__())


class CountryPageLink(models.Model):
    '''
    This model holds the country specific link to an external site.
    The set of these links per site are defined by the FK relationship
    to a LinkSet model instance
    '''

    country = CountryField()
    url = models.URLField(unique=True)
    linkset = models.ForeignKey(LinkSet, related_name='link_set')

    def __repr__(self):
        return '{},{},{}'.format(self.id, self.country, self.url,)

    def __str__(self):
        return str(self.__repr__())

    def __unicode__(self):
        return u'{}'.format(self.__repr__())

demosite/countrydemo/forms.py
from django import forms

from django_countries.widgets import CountrySelectWidget

from django_countries import countries
from . import models

class CountryLinkForm(forms.Form):
    country_code = forms.CharField(label='country code', max_length=2)



class CountryInfoForm(forms.ModelForm):

    class Meta:
        model = models.CountryInfo
        #fields = ('notes', 'country')
        fields = ('notes',)


class ChooseCountryForm(forms.Form):
    country = forms.ChoiceField(choices=countries,
                                label="country_select",
                                initial='US',
                                #widget=forms.Select(),
                                required=True,)


class UpdateCountryInfoForm(forms.ModelForm):
    class Meta:
        model = models.CountryInfo
        fields = ('notes',)

demosite/countrydemo/views.py
import logging

from django.core.urlresolvers import (
    reverse_lazy,
    )
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import (
    DetailView,
    FormView,
    ListView,
    UpdateView,
    )
from django.views.generic.edit import FormMixin
from django_countries.widgets import CountrySelectWidget

from .forms import (
        UpdateCountryInfoForm,
        ChooseCountryForm,
    )
from .models import (
    CountryInfo,
    LinkSet,
    CountryPageLink,
)


logger = logging.getLogger(__name__)

def index(request):
    return render(request, 'countrydemo/index.html', {})


def wikipedia_pages(request):
    '''
    Show the flags and links for wikipedia pages
    '''
    label = 'Wikipedia'
    linkset = LinkSet.objects.get(label=label)
    country_page_links = CountryPageLink.objects.filter(linkset=linkset)
    context = {
        'linkset': linkset,
        'country_page_links': country_page_links,
        'label': label,
    }
    return render(request, 'countrydemo/country_pages.html', context)


class CountryInfoListView(FormMixin, ListView):
    '''
    Provide countries
    '''

    model = CountryInfo
    template_name = 'countrydemo/country_info_list.html'
    form_class = ChooseCountryForm
    def get_context_data(self, **kwargs):
        context = super(CountryInfoListView, self).get_context_data(**kwargs)
        
        return context

    def get_success_url(self):
        logger.info('CountryInfoListView.get_success_url called...')
        return reverse('country-info-list-view')

    def post(self, request, *args, **kwargs):
        logger.info('CountryInfoListView.post called')
        logger.info('args={}'.format(args))
        logger.info('kwargs={}'.format(kwargs))

        country = request.POST.get('country')
        country_info = CountryInfo.objects.get(country=country)
        context = { 'pk': country_info.pk}

        return HttpResponseRedirect(reverse('countrydemo:country-info-detail-view',
            kwargs={ 'pk': country_info.pk}))


class CountryInfoDetailView(DetailView):
    '''

    '''

    model = CountryInfo
    template_name = 'countrydemo/country_info_detail.html'

    def get_info_links(self):
        return CountryPageLink.objects.filter(country=self.object.country)

    def get_context_data(self, **kwargs):
        context = super(CountryInfoDetailView, self).get_context_data(**kwargs)
        context['info_links'] = self.get_info_links()
        return context


class CountryInfoUpdateView(UpdateView):
    '''

    '''

    context_object_name = 'country_info'
    form_class = UpdateCountryInfoForm
    template_name = 'countrydemo/country_info_update_form.html'

    def get_object(self, queryset=None):
        return CountryInfo.objects.get(id=self.kwargs['pk'])

    def get_success_url(self):
        return reverse('countrydemo:country-info-detail-view',
            kwargs={ 'pk': self.object.pk })

demosite/countrydemo/templates/countrydemo/_country_select_form.html
<form action="{% url 'countrydemo:country-info-list-view' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}

  <input type="submit" value="Send request">
</form>

demosite/countrydemo/templates/countrydemo/about.html
{% extends "base.html" %}

{% block navigation %}
{% include 'countrydemo/navigation.html' %}
{% endblock %}

{% block content %}
<p>This page provides some information and links about this demo and the Django Countries package
</p>

<ul>
<li><a href="https://github.com/johnbaldwin/django-countries-demo">Country Demo Repository</a></li>
<li><a href="https://github.com/SmileyChris/django-countries">Django Countries Github Repository</a></li>
</ul>
{% endblock %}

demosite/countrydemo/templates/countrydemo/country_info_detail.html
{% extends "base.html" %}
{% block navigation %}
{% include 'countrydemo/navigation.html' %}
{% endblock %}

{% block content %}
<div class='country-detail'>
  <h1>Country Info Detail</h1>

  <a href="{% url 'countrydemo:country-info-list-view' %}">CountryInfo List page</a>

  <h2>Country: {{ object.country.name }}</h2>
  <div class='notes'>
    <h3>Notes:</h3>
    {% if object.notes %}
      <p>{{ object.notes|linebreaks }}</p>
    {% else %}
      <p class='no_notes_comment'>No notes</p>
    {% endif %}
    <div>
      <a href='{% url 'countrydemo:country-info-update-view' object.id %}'>update</a>
    </div>
  </div>
  <div>
    {% if info_links %}
      <h3>Information links</h3>
      <ul>
        {% for info_link in info_links %}
          <li><a href="{{ info_link.url }}" target="_blank">{{ info_link.linkset.label }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <div> no info links </div>
    {% endif %}
  </div>  
</div>
{% endblock %}

demosite/countrydemo/templates/countrydemo/country_info_list.html
{% load countries %}

<h1>Country Info pages</h1>


<div>
{% get_country 'US' as this_country %}
You are here: {{ this_country.name }}
</div>

{% include 'countrydemo/_country_select_form.html' %}

<div>
{% if show_country_list %}
  {% if object_list %}
    <ul>
      {% for country_info in object_list %}
        <li>{{ country_info.country.name }}</li>
      {% endfor %}
    </ul>

  {% else %}
    <p>No country info. Add some!</p>
  {% endif %}
{% endif %}
</div>

demosite/countrydemo/templates/countrydemo/country_info_update_form.html
{% extends "base.html" %}

{% load static %}

{% block navigation %}
{% include 'countrydemo/navigation.html' %}
{% endblock %}

{% block content %}
<form action="" method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update" />
</form>
{% endblock %}

demosite/countrydemo/templates/countrydemo/country_pages.html
{% extends "base.html" %}

{% load static %}

{% block navigation %}
{% include 'countrydemo/navigation.html' %}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'flags/sprite.css' %}">
<h1>{{ label }} Country Pages</h1>
<ul>
  {% for cpl in country_page_links %}
  <li>
    <i class="{{ cpl.country.flag_css }}"></i>
    <a href="{{ cpl.url }}" target="_blank"> {{ cpl.country.name }}</a>

  </li>
  {% endfor %}
</ul>
{% endblock %}

demosite/countrydemo/templates/countrydemo/index.html
{% extends "base.html" %}
{% block navigation %}
{% include 'countrydemo/navigation.html' %}
{% endblock %}
{% block content %}
<h1>Country Demo</h1>

<ul>
  <li>
    <a href="{% url 'countrydemo:country-demo-about' %}">About this application</a>
  </li>
  <li>
    <a href="{% url 'countrydemo:country-pages' %}">Wikipedia Country Pages</a>
  </li>
  <li>
    <a href="{% url 'countrydemo:country-info-list-view' %}">CountryInfo List page</a>
  </li>
</ul>

{% endblock %}

demosite/countrydemo/templates/countrydemo/navigation.html
<h3>Navigation</h3>
<ul>
  <li><a href="/">Site Home</a></li>
  <li><a href="{% url 'countrydemo:index' %}">Country Demo Index</a></li>
</ul>

demosite/demosite/templates/base.html
<!DOCTYPE html>
<html lang="{% block html_language_code %}en{% endblock %}">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Demosite{% endblock %} </title>
  </head>
  <body id="{% block sectionid %}generic{% endblock %}" class="{% block body_class %}{% endblock %}">
    {% block navigation %}{% endblock %}
    {% block content %}{% endblock %}
  </body>
</html>

demosite/demosite/templates/homepage.html
{% extends "base.html" %}
{% block content %}
<h1>Demo Site Homepage</h1>


<a href="{% url 'countrydemo:index' %}">Country Demo Index</a>

{% endblock %}